//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int Id { get; set; }
        public int JobId { get; set; }
        public int UserId { get; set; }
        public string CoverLetter { get; set; }
        public string CVPath { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Status { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
